[#11] 유저 매칭
f-lab-edu/MAME_Java pull request #12
Opened 2024-05-28 08:40 UTC by DanteRoyal

2024-05-28 19:40 UTC, kee1993 requested changes
일단 전반적으로괜찮은데, private function public function 이파트 전반적으로 다 한번 체크해주시고, private으로 둘것들은 꼭 private으로해놔주세요.

지금 멤버로 바꿧는데 원래이러면 repository도 멤버로 바꾸는게 통일성이더좋을수있어요, 이거는 나중에 따로 처리하시던지 하면좋을것같아요.

2024-05-28 19:40 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/KakaoMapsApi.java
> +		String url = "https://dapi.kakao.com/v2/local/search/address.json?query=";
private variable로 하던지 config으로 따로 하는게좋습니다.

2024-05-28 19:40 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/KakaoMapsApi.java
> +		return response.getDocuments().get(0);
이런코드들은 왜 첫번째를가져오는지 에대한 설명이부족해서, 다른방법으로 mapping을하든 클래스를만들든 좀더 이해하기쉽게 하는게좋아요.

2024-05-28 19:40 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/ProfileService.java
> +	public Point addLocation(Double longitude, Double latitude) {
클래스내에서는 콜하면 private으로 바꿔주세요,

2024-05-28 19:40 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/domain/ProfileRepository.java
> +	@Query(value = "select * from Profile p "
이부분 리팩토링 나중에 고민해보면좋습니다. SQL 쿼리가 직접들어간경우는 확실히 쿼리가 직감적으로 이해가되고 다시 쓰기도 쉬워야되는데 이런쿼리들이 디버깅하기가 어려울수있습니다. 지금은괜찮을것같아요.

2024-05-29 05:45 UTC, DanteRoyal commented on src/main/java/com/flab/mame/profile/KakaoMapsApi.java
> +		return response.getDocuments().get(0);
API가 응답을 List형태로 반환하여 리스트이 첫번째값만 받아오려고해서 위와같이 구현했는데 List가 아닌 단 한건의 데이터만 받아올수 있는 방법이 없을지 고민중이였습니다

2024-05-29 05:56 UTC, DanteRoyal commented on src/main/java/com/flab/mame/profile/domain/ProfileRepository.java
> +	@Query(value = "select * from Profile p "
추후에 QueryDSL로 바꾸는게 나을까요?

2024-05-29 07:26 UTC, DanteRoyal commented on src/main/java/com/flab/mame/profile/KakaoMapsApi.java
> +		String url = "https://dapi.kakao.com/v2/local/search/address.json?query=";
config라는게 어떤것을 말씀하시는건가요?

2024-05-29 07:30 UTC, merged