Profile CRUD
f-lab-edu/MAME_Java pull request #2
Opened 2024-05-16 04:35 UTC by DanteRoyal

profile 엔티티, 컨트롤러, 레포지터리, Dto 생성

2024-05-19 01:06 UTC, kee1993 requested changes
전반적으로 좋습니다 작은디테일인데 변수명들조금더 고민하시고 이제 예외처리같은것들 더넣으시면조흘것같아요.

2024-05-19 01:06 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/Profile.java
> +	public void update(final ProfileUpdateRequest request) {
메소드명이 너무 generral해요, 그냥 이 메소드이름으로도 무엇을하는지 알수있도록 좀 고민하면좋아요,.

2024-05-19 01:06 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/Profile.java
> +	private String bio;
마찬가지로 bio가뭔지 더 이름디테일

2024-05-19 01:06 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/Profile.java
> +	private String gender;
gender같ㅇ느경우 enum같은거로 관맇쉽게해주세요.

2024-05-19 01:06 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/Profile.java
> +	public void update(final ProfileUpdateRequest request) {
또그리고 input validation check도 하면좋습니다.

2024-05-19 01:06 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/ProfileService.java
> +	public Profile createProfile(final ProfileCreateRequest request) {
validation넣어주세요.

2024-05-19 01:06 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/ProfileService.java
> +public class ProfileService {
전반적인 예외처리를 좀더 넣어주세요 디테일하게.

2024-05-19 01:06 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/ProfileService.java
> +	public Profile findById(final Long id) {
findById를 쓰실꺼면 다른것도 id로 하는거도 통일을하든지 하면좋아요.

2024-05-19 01:06 UTC, kee1993 commented on src/main/java/com/flab/mame/profile/ProfileController.java
> +	public Profile getProfileDetail(@PathVariable final Long id) {
프로필인지 디테일인지 좀 통일을 하면좋을것같아요.

2024-05-20 02:00 UTC, DanteRoyal commented on src/main/java/com/flab/mame/profile/ProfileService.java
> +	public Profile createProfile(final ProfileCreateRequest request) {
controller랑 dto에 넣어놨는데 service에도 validation을 하는 방법이 있나요?

2024-05-20 04:08 UTC, merged